export const FOCUS_EVENT_VIEW = 'FOCUS_EVENT_VIEW';
export const DEFOCUS_EVENT_VIEW = 'DEFOCUS_EVENT_VIEW';

export const FOCUS_EVENT_FORM =  'FOCUS_EVENT_FORM';
export const DEFOCUS_EVENT_FORM =  'DEFOCUS_EVENT_FORM';
