export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR';

export const FETCH_EVENT_DETAIL_REQUEST = 'FETCH_EVENT_DETAIL_REQUEST';
export const FETCH_EVENT_DETAIL_SUCCESS = 'FETCH_EVENT_DETAIL_SUCCESS';
export const FETCH_EVENT_DETAIL_ERROR = 'FETCH_EVENT_DETAIL_ERROR';

export const POST_EVENT_REQUEST = 'POST_EVENT_REQUEST';
export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
export const POST_EVENT_ERROR = 'POST_EVENT_ERROR';

export const ADD_EVENT_RESOURCE_REQUEST = 'ADD_EVENT_RESOURCE_REQUEST'
export const ADD_EVENT_RESOURCE_SUCCESS = 'ADD_EVENT_RESOURCE_SUCCESS'
export const ADD_EVENT_RESOURCE_ERROR = 'ADD_EVENT_RESOURCE_ERROR'
